/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
export namespace Components {
  interface PlannerDay {
    day: string;
    /**
     * @default ''
     */
    recipeImage: string;
    /**
     * @default ''
     */
    recipeTitle: string;
  }
  interface RecipeCard {
    /**
     * @default ''
     */
    category: string;
    /**
     * @default ''
     */
    cuisine: string;
    /**
     * @default false
     */
    favorite: boolean;
    /**
     * @default ''
     */
    image: string;
    recipeId: string;
    recipeTitle: string;
  }
}
export interface PlannerDayCustomEvent<T> extends CustomEvent<T> {
  detail: T;
  target: HTMLPlannerDayElement;
}
export interface RecipeCardCustomEvent<T> extends CustomEvent<T> {
  detail: T;
  target: HTMLRecipeCardElement;
}
declare global {
  interface HTMLPlannerDayElementEventMap {
    removeMeal: void;
  }
  interface HTMLPlannerDayElement extends Components.PlannerDay, HTMLStencilElement {
    addEventListener<K extends keyof HTMLPlannerDayElementEventMap>(
      type: K,
      listener: (
        this: HTMLPlannerDayElement,
        ev: PlannerDayCustomEvent<HTMLPlannerDayElementEventMap[K]>,
      ) => any,
      options?: boolean | AddEventListenerOptions,
    ): void;
    addEventListener<K extends keyof DocumentEventMap>(
      type: K,
      listener: (this: Document, ev: DocumentEventMap[K]) => any,
      options?: boolean | AddEventListenerOptions,
    ): void;
    addEventListener<K extends keyof HTMLElementEventMap>(
      type: K,
      listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any,
      options?: boolean | AddEventListenerOptions,
    ): void;
    addEventListener(
      type: string,
      listener: EventListenerOrEventListenerObject,
      options?: boolean | AddEventListenerOptions,
    ): void;
    removeEventListener<K extends keyof HTMLPlannerDayElementEventMap>(
      type: K,
      listener: (
        this: HTMLPlannerDayElement,
        ev: PlannerDayCustomEvent<HTMLPlannerDayElementEventMap[K]>,
      ) => any,
      options?: boolean | EventListenerOptions,
    ): void;
    removeEventListener<K extends keyof DocumentEventMap>(
      type: K,
      listener: (this: Document, ev: DocumentEventMap[K]) => any,
      options?: boolean | EventListenerOptions,
    ): void;
    removeEventListener<K extends keyof HTMLElementEventMap>(
      type: K,
      listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any,
      options?: boolean | EventListenerOptions,
    ): void;
    removeEventListener(
      type: string,
      listener: EventListenerOrEventListenerObject,
      options?: boolean | EventListenerOptions,
    ): void;
  }
  var HTMLPlannerDayElement: {
    prototype: HTMLPlannerDayElement;
    new (): HTMLPlannerDayElement;
  };
  interface HTMLRecipeCardElementEventMap {
    recipeSelected: string;
    favoriteChanged: {
      id: string;
      favorite: boolean;
    };
  }
  interface HTMLRecipeCardElement extends Components.RecipeCard, HTMLStencilElement {
    addEventListener<K extends keyof HTMLRecipeCardElementEventMap>(
      type: K,
      listener: (
        this: HTMLRecipeCardElement,
        ev: RecipeCardCustomEvent<HTMLRecipeCardElementEventMap[K]>,
      ) => any,
      options?: boolean | AddEventListenerOptions,
    ): void;
    addEventListener<K extends keyof DocumentEventMap>(
      type: K,
      listener: (this: Document, ev: DocumentEventMap[K]) => any,
      options?: boolean | AddEventListenerOptions,
    ): void;
    addEventListener<K extends keyof HTMLElementEventMap>(
      type: K,
      listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any,
      options?: boolean | AddEventListenerOptions,
    ): void;
    addEventListener(
      type: string,
      listener: EventListenerOrEventListenerObject,
      options?: boolean | AddEventListenerOptions,
    ): void;
    removeEventListener<K extends keyof HTMLRecipeCardElementEventMap>(
      type: K,
      listener: (
        this: HTMLRecipeCardElement,
        ev: RecipeCardCustomEvent<HTMLRecipeCardElementEventMap[K]>,
      ) => any,
      options?: boolean | EventListenerOptions,
    ): void;
    removeEventListener<K extends keyof DocumentEventMap>(
      type: K,
      listener: (this: Document, ev: DocumentEventMap[K]) => any,
      options?: boolean | EventListenerOptions,
    ): void;
    removeEventListener<K extends keyof HTMLElementEventMap>(
      type: K,
      listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any,
      options?: boolean | EventListenerOptions,
    ): void;
    removeEventListener(
      type: string,
      listener: EventListenerOrEventListenerObject,
      options?: boolean | EventListenerOptions,
    ): void;
  }
  var HTMLRecipeCardElement: {
    prototype: HTMLRecipeCardElement;
    new (): HTMLRecipeCardElement;
  };
  interface HTMLElementTagNameMap {
    'planner-day': HTMLPlannerDayElement;
    'recipe-card': HTMLRecipeCardElement;
  }
}
declare namespace LocalJSX {
  type OneOf<K extends string, PropT, AttrT = PropT> =
    | ({ [P in K]: PropT } & { [P in `attr:${K}`]?: never })
    | ({ [P in `attr:${K}`]: AttrT } & { [P in K]?: never });

  interface PlannerDay {
    day: string;
    onRemoveMeal?: (event: PlannerDayCustomEvent<void>) => void;
    /**
     * @default ''
     */
    recipeImage?: string;
    /**
     * @default ''
     */
    recipeTitle?: string;
  }
  interface RecipeCard {
    /**
     * @default ''
     */
    category?: string;
    /**
     * @default ''
     */
    cuisine?: string;
    /**
     * @default false
     */
    favorite?: boolean;
    /**
     * @default ''
     */
    image?: string;
    onFavoriteChanged?: (
      event: RecipeCardCustomEvent<{
        id: string;
        favorite: boolean;
      }>,
    ) => void;
    onRecipeSelected?: (event: RecipeCardCustomEvent<string>) => void;
    recipeId: string;
    recipeTitle: string;
  }

  interface PlannerDayAttributes {
    day: string;
    recipeTitle: string;
    recipeImage: string;
  }
  interface RecipeCardAttributes {
    recipeId: string;
    recipeTitle: string;
    image: string;
    category: string;
    cuisine: string;
    favorite: boolean;
  }

  interface IntrinsicElements {
    'planner-day': Omit<PlannerDay, keyof PlannerDayAttributes> & {
      [K in keyof PlannerDay & keyof PlannerDayAttributes]?: PlannerDay[K];
    } & {
      [K in keyof PlannerDay & keyof PlannerDayAttributes as `attr:${K}`]?: PlannerDayAttributes[K];
    } & {
      [K in keyof PlannerDay & keyof PlannerDayAttributes as `prop:${K}`]?: PlannerDay[K];
    } & OneOf<'day', PlannerDay['day'], PlannerDayAttributes['day']>;
    'recipe-card': Omit<RecipeCard, keyof RecipeCardAttributes> & {
      [K in keyof RecipeCard & keyof RecipeCardAttributes]?: RecipeCard[K];
    } & {
      [K in keyof RecipeCard & keyof RecipeCardAttributes as `attr:${K}`]?: RecipeCardAttributes[K];
    } & {
      [K in keyof RecipeCard & keyof RecipeCardAttributes as `prop:${K}`]?: RecipeCard[K];
    } & OneOf<'recipeId', RecipeCard['recipeId'], RecipeCardAttributes['recipeId']> &
      OneOf<'recipeTitle', RecipeCard['recipeTitle'], RecipeCardAttributes['recipeTitle']>;
  }
}
export { LocalJSX as JSX };
declare module '@stencil/core' {
  export namespace JSX {
    interface IntrinsicElements {
      'planner-day': LocalJSX.IntrinsicElements['planner-day'] &
        JSXBase.HTMLAttributes<HTMLPlannerDayElement>;
      'recipe-card': LocalJSX.IntrinsicElements['recipe-card'] &
        JSXBase.HTMLAttributes<HTMLRecipeCardElement>;
    }
  }
}
